version: "3.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "node.name=es01"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    volumes:
      - ./logstash:/usr/share/logstash/pipeline:ro
      - ./dataset:/var/log/dataset:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  product-service:
    build:
      dockerfile: ./src/grpc/Dockerfile
    ports:
      - "10001:10001"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  graph-ql:
    build:
      dockerfile: ./src/api/Dockerfile
    ports:
      - "10002:10002"
    networks:
      - elk
    depends_on:
      - product-service
    links:
      - product-service

networks:
  elk:
    driver: bridge

volumes:
  es-data:
    driver: local