version: 3.3

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    volumes:
      - ./logstash:/usr/share/logstash/pipeline:ro
      - ./dataset:/var/log/dataset:ro
    ports:
      - "5000:5000"
    networks:
      - elk
    depends_on:
      - elastic
    links:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  es-data:
    driver: local