// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	Category            *string   `json:"category"`
	Subcategory         *string   `json:"subcategory"`
	Name                *string   `json:"name"`
	CurrentPrice        *float64  `json:"currentPrice"`
	RawPrice            *float64  `json:"rawPrice"`
	Currency            *string   `json:"currency"`
	Discount            *int      `json:"discount"`
	LikesCount          *int      `json:"likesCount"`
	IsNew               *bool     `json:"isNew"`
	Brand               *string   `json:"brand"`
	BrandURL            *string   `json:"brandUrl"`
	CodCountry          []*string `json:"codCountry"`
	Variation0Color     *string   `json:"variation0Color"`
	Variation1Color     *string   `json:"variation1Color"`
	Variation0Thumbnail *string   `json:"variation0Thumbnail"`
	Variation0Image     *string   `json:"variation0Image"`
	Variation1Thumbnail *string   `json:"variation1Thumbnail"`
	Variation1Image     *string   `json:"variation1Image"`
	ImageURL            *string   `json:"imageUrl"`
	URL                 *string   `json:"url"`
	ID                  *string   `json:"id"`
	Model               *string   `json:"model"`
}
